version: '3.9'
services:
  db:
    image: mongo:7.0.1
    restart: on-failure
    volumes:
      - dbdata:/data/db
    ports:
      - "${DB_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/admin --quiet
      interval: 5s
      timeout: 10s
      retries: 5

  backend:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "${HTTP_PORT}:8000"
    depends_on:
      - db

volumes:
  dbdata:
